### ISSUE TITLE
docker_builder task cannot use 'docker-compose up --build' throws 'ImportError'

### ISSUE THREAD

**Issue by northkevin** [cirruslabs/cirrus-ci-docs#424]
# Expected Behavior

docker-compose utility should attempt to run 'up' command against the 'docker-compose.yml' in the current directory.

# Real Behavior
The command does not execute properly & the following error is displayed - 

`ImportError: No module named ssl_match_hostname`

I can workaround the issue by adding the following task to my .cirrus.yml ..

```
compose_script:
    - pip uninstall -y docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - mv docker-compose /usr/local/bin
```

Here is the stacktrace - 

```
docker-compose -f docker-compose.yml up --build
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

# Related Info

- [ ] Website issue
  - Link to page: 
  - Link to build where message occurs - https://cirrus-ci.com/task/6293136437936128?command=compose#L78
- [ ] Task issue
  - OS: (DockerLinux, macOS, Windows, FreeBSD)
  - Task name: docker_builder
  - Script/cache name (if applies):

**Comment by RDIL** [comment]
Hey @northkevin!
You can fix this by adding the following to the end of the install script:
```yaml
  - python -m pip install --upgrade backports.ssl_match_hostname
```
Let us know if you have any further problems :)

**Comment by fkorotkov** [comment]
@RDIL seems like another workaround. Will update the builder image as well. 🙌

**Comment by fkorotkov** [comment]
Oh. Sorry this issue got out of my radar. Docker Builder VM just got updated and should contain a fix for the issue (see https://github.com/cirruslabs/vm-images/commit/407157232b49b870131c3ebbb3a0e931417dc176).
