### ISSUE TITLE
freebsd-11-3-release-amd64 agent not responding

### ISSUE THREAD

**Issue by koitsu** [cirruslabs/cirrus-ci-docs#686]
Can someone check the status of launching a `freebsd_instance` with `image: freebsd-11-3-release-amd64` ? For the past couple days I've seen nothing but *Agent is not responding!*.  For whatever reason, 11.4 and 12.x seem to work fine.

Thank you!

**Comment by fkorotkov** [comment]
Seems FreeBSD images are broken again.

<summary>
Google Instance Logs
<details>
```console
Starting google_instance_setup.
Traceback (most recent call last):
  File "/usr/local/bin/google_instance_setup-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine
/etc/rc: WARNING: failed to start google_instance_setup
Starting google_network_daemon.
Starting google_accounts_daemon.
Starting google_clock_skew_daemon.
Traceback (most recent call last):
  File "/usr/local/bin/google_clock_skew_daemon-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine
Traceback (most recent call last):
  File "/usr/local/bin/google_metadata_script_runner-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine
Traceback (most recent call last):
  File "/usr/local/bin/google_accounts_daemon-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine
Traceback (most recent call last):
  File "/usr/local/bin/google_network_daemon-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'boto' distribution was not found and is required by google-compute-engine
```
</details>
</summary>

Seems like a duplicate of #359. Don't recall of 11.3 was ever fixed. Was it working for you before?

**Comment by koitsu** [comment]
> Seems like a duplicate of #359. Don't recall of 11.3 was ever fixed. Was it working for you before?

Good question -- unsure. I just recently (a day or two ago) added references to it in my `.cirrus.yml`.  Here's what my current analysis shows, as of 24-48 hours ago:

- `freebsd-13-0-snap` -- fails: **Failed to start an instance: INVALID_ARGUMENT: Bad Request**
- `freebsd-12-1-snap` -- haven't tried
- `freebsd-12-1-release-amd64` -- works
- `freebsd-12-0-release-amd64` -- works (but EoL'd)
- `freebsd-11-4-release-amd64` -- works
- `freebsd-11-3-snap` -- haven't tried
- `freebsd-11-3-release-amd64` -- fails (reported here)
- `freebsd-11-2-release-amd64` -- works (but EoL'd)
- `freebsd-11-1-release-amd64` -- works (but EoL'd)
- `freebsd-11-0-release-p1-amd64` -- works (but EoL'd)
- `freebsd-10-4-release-amd64` -- works
- `freebsd-10-3-release-amd64` -- works (but EoL'd)
- `freebsd-10-2-release-amd64` -- works (but EoL'd)

I didn't know this until today, but it seems [the FreeBSD Project itself maintains the GCE images](https://cloud.google.com/compute/docs/images#freebsd).  I might propose that Cirrus CI's docs copy-paste that exact clause from Google's, since had I known this I wouldn't have filed a ticket here (i.e. I thought Cirrus CI maintained the images used).

I also thought what was shown at the bottom of the Cirrus CI page was a list of *images*, when in fact it's a list of *families*.  I didn't know you could refer to an image *family*, I thought you had to explicitly refer to an image.  So this was a learning experience for me just responding!

I'll close this out because the images not the fault of Cirrus CI.  The fault looks to be due to FreeBSD Ports screwing around with Python 2.x deprecation and breaking all sorts of things.  There's discussions on freebsd-ports about this already.
